version: "3.8"

services:
  mc:
    image: itzg/minecraft-server
    container_name: minecraft
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
      - "24454:24454/udp" # for Simple Voice Chat
    environment:
      EULA: "TRUE"
      VERSION: 1.20.1
      DIFFICULTY: normal
      MOTD: "Infinite Horizons | Powered by sunshine \u2600"
      MOD_PLATFORM: MODRINTH
      MODRINTH_MODPACK: https://modrinth.com/modpack/infinite-horizons
      # VIEW_DISTANCE: 10
      OVERRIDE_SERVER_PROPERTIES: "TRUE"
      ICON: https://cdn.modrinth.com/data/XQqzgjF0/79a864cfc58c78ae53edc20d889716782eef544c.jpeg
      # MAX_TICK_TIME: "-1"
      # AUTOPAUSE_TIMEOUT_INIT: "60"
      # AUTOPAUSE_TIMEOUT_EST: "60"
      # STOP_SERVER_ANNOUNCE_DELAY: 30
    restart: unless-stopped
    volumes:
      # attach the relative directory 'data' to the container's /data path
      - ./data:/data
